# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_updatekeyWordTree <- function(clone_sequences, ndn_start_vec, ndn_end_vec, clone_idx, packed_tree) {
    .Call(`_EOS_C_updatekeyWordTree`, clone_sequences, ndn_start_vec, ndn_end_vec, clone_idx, packed_tree)
}

C_findMatchingIdx <- function(clone_sequences, max_dist, ndn_cost, packed_tree) {
    .Call(`_EOS_C_findMatchingIdx`, clone_sequences, max_dist, ndn_cost, packed_tree)
}

C_getLocus <- function(cloneResolved, vFamilyName, vFamilyTies, dFamilyName, dFamilyTies, jFamilyName, jFamilyTies) {
    .Call(`_EOS_C_getLocus`, cloneResolved, vFamilyName, vFamilyTies, dFamilyName, dFamilyTies, jFamilyName, jFamilyTies)
}

C_determineCdr3Index <- function(cloneLength, vIndex, dIndex, cdr3Length) {
    .Call(`_EOS_C_determineCdr3Index`, cloneLength, vIndex, dIndex, cdr3Length)
}

